<?php
session_start();
if (!isset($_SESSION['teacher_id'])) {
    header("Location: ../login/index.php");
    exit();
}

include('processes/server/conn.php');

$class_name = $_GET['class_id'] ?? '';
$teacher = $_SESSION['full_name'];

// Verify teacher has access to this class (same security check as original page)
$sa_stmt = $pdo->prepare("
    SELECT id, class_advising
    FROM staff_advising
    WHERE fullName = :teacher
      AND class_advising = :class_name
    LIMIT 1
");
$sa_stmt->execute(['teacher' => $teacher, 'class_name' => $class_name]);
$staff_advising = $sa_stmt->fetch(PDO::FETCH_ASSOC);

if (!$staff_advising) {
    die("You are not authorized for this class.");
}

// Get students (same query as original page)
$students_stmt = $pdo->prepare("
    SELECT s.*
    FROM students s
    JOIN students_advising sa ON sa.student_id = s.id
    WHERE sa.staff_advising_id = :sa_id
    ORDER BY s.last_name, s.first_name
");
$students_stmt->execute(['sa_id' => $staff_advising['id']]);
$students = $students_stmt->fetchAll(PDO::FETCH_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Class Roster - <?= htmlspecialchars($class_name) ?></title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #000;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 14px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background-color: #10177a;
            color: white;
            text-align: center;
            padding: 8px;
            border: 1px solid #ddd;
        }
        td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: left;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
        .student-photo {
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 50%;
            display: block;
            margin: 0 auto;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 12px;
        }
        @page {
            size: auto;
            margin: 10mm;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Advisory Class: <?= htmlspecialchars($class_name) ?></h1>
        <p>Class Roster - Printed on <?= date('F j, Y') ?></p>
        <p>Adviser: <?= htmlspecialchars($teacher) ?></p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Photo</th>
                <th>Student ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($students as $student): ?>
                <tr>
                    <td style="text-align: center;">
                        <?php if (!empty($student['photo'])): ?>
                            <img src="../uploads/students/<?= htmlspecialchars($student['photo']) ?>" 
                                 class="student-photo"
                                 alt="Student photo">
                        <?php else: ?>
                            <div class="student-photo" style="background-color: #eee;"></div>
                        <?php endif; ?>
                    </td>
                    <td><?= htmlspecialchars($student['student_id']) ?></td>
                    <td><?= htmlspecialchars($student['last_name']) ?>, <?= htmlspecialchars($student['first_name']) ?></td>
                    <td><?= htmlspecialchars($student['email']) ?></td>
                    <td><?= htmlspecialchars($student['contact_number'] ?? 'N/A') ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by AdNU - CCS Student Management System</p>
    </div>

    <script>
        // Automatically trigger print dialog when page loads
        window.onload = function() {
            setTimeout(function() {
                window.print();
                // Close the window after printing (optional)
                setTimeout(function() {
                    window.close();
                }, 500);
            }, 200);
        };
    </script>
</body>
</html>